#!/usr/bin/env bash
set -euo pipefail

# Compare BE / DOE / OOE encodings for a circuit across observation indices.
# It runs the existing binary once per observation and collects:
# - WCNF header metrics: vars, clauses, top
# - optional solver runtime/exit status for each generated WCNF
#
# Usage:
#   ./compare_ooe_doe.sh \
#     --bin ./main_test \
#     --sys sys_server/c17.sys \
#     --txt sys_server/c17.txt \
#     --syspp sys_server/c17.syspp \
#     --obs iscas85/c17_iscas85.obs \
#     --start 1 --end 63 \
#     --out results_c17.csv \\
#     --mode all
#
# Optional solver (placeholder {wcnf} is required):
#   --solver-cmd "python3 -m pysat.examples.rc2 -c b {wcnf}"
#   --solver-timeout 10

usage() {
  cat <<'EOF'
Usage:
  compare_ooe_doe.sh --bin BIN --sys SYS --txt TXT --syspp SYSPP --obs OBS --start N --end M --out CSV
Optional:
  --solver-cmd CMD_TEMPLATE   External solver command; must contain {wcnf}
  --solver-timeout SEC        Timeout for solver command (default: 10)
  --mode MODE                 Pass mode to target binary: be|doe|ooe|all

Notes:
  1) This script expects your program to emit:
     - remain_clauses.wcnf   (BE)
     - remain_clauses1.wcnf  (DOE)
     - remain_clauses2.wcnf  (OOE)
  2) If DOE/OOE files are not generated by current build, related fields are left empty.
  3) Paths passed to the target binary are normalized by removing leading ./
     to avoid parser issues in the current codebase.
EOF
}

require_arg() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "[ERROR] Missing required argument: $name" >&2
    usage
    exit 2
  fi
}

normalize_for_target() {
  local p="$1"
  if [[ "$p" == ./* ]]; then
    echo "${p:2}"
  else
    echo "$p"
  fi
}

parse_wcnf_header() {
  local f="$1"
  if [[ ! -f "$f" ]]; then
    echo ",,,"
    return 0
  fi

  local header
  header="$(grep -m1 '^p[[:space:]]\+wcnf[[:space:]]' "$f" || true)"
  if [[ -z "$header" ]]; then
    echo ",,,"
    return 0
  fi

  # header format: p wcnf VARS CLAUSES TOP
  local vars clauses top
  vars="$(awk '{print $3}' <<<"$header")"
  clauses="$(awk '{print $4}' <<<"$header")"
  top="$(awk '{print $5}' <<<"$header")"
  echo "$vars,$clauses,$top"
}

run_solver_optional() {
  local wcnf="$1"
  local solver_template="$2"
  local solver_timeout="$3"

  # returns: time_sec,exit_code
  if [[ -z "$solver_template" || ! -f "$wcnf" ]]; then
    echo ","
    return 0
  fi

  local cmd
  cmd="${solver_template//\{wcnf\}/$wcnf}"

  local t0 t1 elapsed rc
  t0="$(date +%s%3N)"
  set +e
  timeout "${solver_timeout}"s bash -lc "$cmd" >/dev/null 2>&1
  rc=$?
  set -e
  t1="$(date +%s%3N)"

  elapsed="$(awk -v a="$t0" -v b="$t1" 'BEGIN{printf "%.3f", (b-a)/1000.0}')"
  echo "$elapsed,$rc"
}

BIN=""
SYS=""
TXT=""
SYSPP=""
OBS=""
START=""
END=""
OUT=""
SOLVER_CMD=""
SOLVER_TIMEOUT="10"
MODE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bin)
      BIN="$2"; shift 2 ;;
    --sys)
      SYS="$2"; shift 2 ;;
    --txt)
      TXT="$2"; shift 2 ;;
    --syspp)
      SYSPP="$2"; shift 2 ;;
    --obs)
      OBS="$2"; shift 2 ;;
    --start)
      START="$2"; shift 2 ;;
    --end)
      END="$2"; shift 2 ;;
    --out)
      OUT="$2"; shift 2 ;;
    --solver-cmd)
      SOLVER_CMD="$2"; shift 2 ;;
    --solver-timeout)
      SOLVER_TIMEOUT="$2"; shift 2 ;;
    --mode)
      MODE="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "[ERROR] Unknown argument: $1" >&2
      usage
      exit 2 ;;
  esac
done

require_arg --bin "$BIN"
require_arg --sys "$SYS"
require_arg --txt "$TXT"
require_arg --syspp "$SYSPP"
require_arg --obs "$OBS"
require_arg --start "$START"
require_arg --end "$END"
require_arg --out "$OUT"

if [[ ! -x "$BIN" ]]; then
  echo "[ERROR] Binary not executable: $BIN" >&2
  exit 2
fi

if ! [[ "$START" =~ ^[0-9]+$ && "$END" =~ ^[0-9]+$ && "$START" -le "$END" ]]; then
  echo "[ERROR] Invalid range: --start $START --end $END" >&2
  exit 2
fi

if [[ -n "$SOLVER_CMD" && "$SOLVER_CMD" != *"{wcnf}"* ]]; then
  echo "[ERROR] --solver-cmd must contain placeholder {wcnf}" >&2
  exit 2
fi

SYS_N="$(normalize_for_target "$SYS")"
TXT_N="$(normalize_for_target "$TXT")"
SYSPP_N="$(normalize_for_target "$SYSPP")"
OBS_N="$(normalize_for_target "$OBS")"

work_dir="$(pwd)"
mkdir -p "$(dirname "$OUT")"

echo "obs,run_exit,be_vars,be_clauses,be_top,doe_vars,doe_clauses,doe_top,ooe_vars,ooe_clauses,ooe_top,be_solve_sec,be_solve_rc,doe_solve_sec,doe_solve_rc,ooe_solve_sec,ooe_solve_rc" > "$OUT"

echo "[INFO] Running compare from obs=$START to obs=$END"
for ((idx=START; idx<=END; idx++)); do
  rm -f remain_clauses.wcnf remain_clauses1.wcnf remain_clauses2.wcnf

  set +e
  if [[ -n "$MODE" ]]; then
    "$BIN" "$SYS_N" "$TXT_N" "$SYSPP_N" "$OBS_N" "$idx" "$MODE" >/tmp/compare_ooe_doe_run.log 2>&1
  else
    "$BIN" "$SYS_N" "$TXT_N" "$SYSPP_N" "$OBS_N" "$idx" >/tmp/compare_ooe_doe_run.log 2>&1
  fi
  run_rc=$?
  set -e

  be_metrics="$(parse_wcnf_header remain_clauses.wcnf)"
  doe_metrics="$(parse_wcnf_header remain_clauses1.wcnf)"
  ooe_metrics="$(parse_wcnf_header remain_clauses2.wcnf)"

  be_solver="$(run_solver_optional remain_clauses.wcnf "$SOLVER_CMD" "$SOLVER_TIMEOUT")"
  doe_solver="$(run_solver_optional remain_clauses1.wcnf "$SOLVER_CMD" "$SOLVER_TIMEOUT")"
  ooe_solver="$(run_solver_optional remain_clauses2.wcnf "$SOLVER_CMD" "$SOLVER_TIMEOUT")"

  echo "$idx,$run_rc,$be_metrics,$doe_metrics,$ooe_metrics,$be_solver,$doe_solver,$ooe_solver" >> "$OUT"

  if (( idx % 20 == 0 )); then
    echo "[INFO] Processed obs=$idx"
  fi
done

echo "[DONE] CSV written to: $OUT"
echo "[NOTE] If DOE/OOE columns are empty, your current binary did not emit remain_clauses1.wcnf/remain_clauses2.wcnf."